/* Login Page */

export const ACTION_USER_SIGN_IN = 'USER_SIGN_IN';
export type ACTION_USER_SIGN_IN = typeof ACTION_USER_SIGN_IN;

export const ACTION_USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export type ACTION_USER_SIGN_IN_SUCCESS = typeof ACTION_USER_SIGN_IN_SUCCESS;

export const ACTION_USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';
export type ACTION_USER_SIGN_IN_ERROR = typeof ACTION_USER_SIGN_IN_ERROR;
